[package]
name = "mc-blackhole"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
bytes = "1.11.1"
fastnbt = "2.6.1"
flate2 = "1.1.9"
paste = "1.0.15"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = ["full"] }
uuid = { version = "1.23.2", features = ["v4"] }
generics_macro = { path = "./generics_macro" }
cgmath = { version = "0.18.0", features = [
    "swizzle",
], default-features = false }
strum = { version = "0.28.0", features = ["derive", "strum_macros"] }
strum_macros = "0.28.0"
rand = "0.10.1"
noise = { version = "0.9.0", features = ["std"] }
dashmap = "6.2.1"

# Full performance profile because why not lol
[profile.release-perf]
inherits = "release"
# Unsure of these \/
opt-level = 3
lto = true
# Unsure of these /\
codegen-units = 1
debug = false
strip = true
overflow-checks = false
panic = "abort"
